// <auto-generated />
using System;
using CreditsimulacaoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditSimulationApi.Migrations.SimulationDb
{
    [DbContext(typeof(SimulationDbContext))]
    [Migration("20250820204900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("CreditsimulacaoApi.Models.Simulacao", b =>
                {
                    b.Property<int>("idSimulacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("idProduto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("noProduto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("prazo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("valorDesejado")
                        .HasColumnType("TEXT");

                    b.HasKey("idSimulacao");

                    b.ToTable("SIMULACAO");
                });
#pragma warning restore 612, 618
        }
    }
}
