// <auto-generated />
using System;
using CreditsimulacaoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditSimulationApi.Migrations.SimulationDb
{
    [DbContext(typeof(SimulationDbContext))]
    partial class SimulationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("CreditsimulacaoApi.Models.Simulacao", b =>
                {
                    b.Property<int>("idSimulacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxaJuros")
                        .HasColumnType("TEXT");

                    b.Property<long>("TempoExecucaoMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idProduto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("noProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("prazo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("valorDesejado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("valorTotalParcelas")
                        .HasColumnType("TEXT");

                    b.HasKey("idSimulacao");

                    b.ToTable("SIMULACAO");
                });
#pragma warning restore 612, 618
        }
    }
}
