// <auto-generated />
using System;
using CreditsimulacaoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditSimulationApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250820202908_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CreditsimulacaoApi.Models.Produto", b =>
                {
                    b.Property<int>("CoProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CO_PRODUTO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoProduto"));

                    b.Property<string>("NoProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NO_PRODUTO");

                    b.Property<short?>("NuMaximoMeses")
                        .HasColumnType("smallint")
                        .HasColumnName("NU_MAXIMO_MESES");

                    b.Property<short>("NuMinimoMeses")
                        .HasColumnType("smallint")
                        .HasColumnName("NU_MINIMO_MESES");

                    b.Property<decimal>("PcTaxaJuros")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PC_TAXA_JUROS");

                    b.Property<decimal?>("VrMaximo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VR_MAXIMO");

                    b.Property<decimal>("VrMinimo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VR_MINIMO");

                    b.HasKey("CoProduto");

                    b.ToTable("PRODUTO");
                });

            modelBuilder.Entity("CreditsimulacaoApi.Models.Simulacao", b =>
                {
                    b.Property<int>("idSimulacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSimulacao"));

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("idProduto")
                        .HasColumnType("int");

                    b.Property<int>("noProduto")
                        .HasColumnType("int");

                    b.Property<int>("prazo")
                        .HasColumnType("int");

                    b.Property<decimal>("valorDesejado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idSimulacao");

                    b.ToTable("SIMULACAO");
                });
#pragma warning restore 612, 618
        }
    }
}
